In [31]:
%config Completer.use_jedi = False
import cv2
import numpy as np

In [32]:
color = cv2.imread("butterfly.jpg")

In [33]:
cv2.imshow("Image",color)

In [34]:
cv2.moveWindow("Image",0,0)

In [35]:
print(color.shape)

(356, 493, 3)


In [36]:
height,width,channel = color.shape
b,g,r = cv2.split(color)

In [37]:
print(b)

[[ 47  47  48 ... 170 172 174]
 [ 50  48  46 ... 171 173 174]
 [ 53  48  43 ... 168 171 172]
 ...
 [ 43  44  46 ... 103  94  88]
 [ 41  42  45 ... 103  95  92]
 [ 45  46  49 ... 103  97  96]]


In [38]:
print(b.shape)

(356, 493)


In [39]:
z = np.zeros([356,493],'uint8')
print(z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [40]:
rgb_split = np.empty([height,width*3,3],'uint8')

In [41]:
rgb_split[:,0:width] = cv2.merge([b,b,b])

In [42]:
rgb_split[:,width:width*2] = cv2.merge([g,g,g])

In [43]:
rgb_split[:,width*2:width*3] = cv2.merge([r,r,r])

In [44]:
cv2.imshow("Channels",rgb_split)

In [45]:
cv2.moveWindow("Channels",0,height)

In [46]:
hsv = cv2.cvtColor(color,cv2.COLOR_BGR2HSV)

In [47]:
h,s,v = cv2.split(hsv)

In [48]:
hsv_split = np.concatenate((h,s,v),axis =1)

In [49]:
cv2.imshow("Split HSV",hsv_split)

In [50]:
cv2.waitKey(0)
cv2.destroyAllWindows()