In [7]:
%config Completer.use_jedi = False

In [6]:
import numpy as np

In [4]:
mylist = [1,2,3]

In [5]:
type(mylist)

list

In [8]:
np.array(mylist)

array([1, 2, 3])

In [9]:
np.arange(0,10,1) # create a numpy array from start to stop

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
#2d array
row = 10
col = 5
zero_arr = np.zeros(shape=(row,col))
print(zero_arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
type(zero_arr)

numpy.ndarray

In [19]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.random.seed(101)
arr = np.random.randint(low= 0,high= 100,size = 10)
print (arr)

[95 11 81 70 63 87 75  9 77 40]


In [34]:
arr.max()


95

In [35]:
arr.min()

9

In [36]:
arr.argmax()

0

In [37]:
arr.argmin()

7

In [38]:
arr.mean()

60.8

In [40]:
arr.shape

(10,)

In [41]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])